apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: $ca_cert
    server: $api_server_url
  name: $cluster_name
contexts:
- context:
    cluster: $cluster_name
    namespace: $namespace
    user: $user_name
  name: ${cluster_name}-context
current-context: ${cluster_name}-context
preferences: {}
users:
- name: $user_name
  user:
    token: $service_account_token