apiVersion: v1
kind: Config
clusters:
- name: {{ cluster_name }}
  cluster:
    server: https://{{ api_server_ip }}:{{ api_server_port }}
    certificate-authority-data: {{ ca_cert }}
users:
- name: {{ user_name }}
  user:
    token: {{ service_account_token }}
contexts:
- name: my-context
  context:
    cluster: {{ cluster_name }}
    user: {{ user_name }}
current-context: my-context