apiVersion: v1
kind: Config
clusters:
- name: {{ cluster_name }}
  cluster:
    certificate-authority-data: r{{ ca_cert }}
    server: https://{{ api_server_ip }}:{{ api_server_port }}
contexts:
- name: {{ context-name }}
  context:
    cluster: {{ cluster_name }}
    namespace: {{ namespace }}
    user: {{ user_name }}
current-context: {{ context-name }}
users:
- name: {{ user_name }}
  user:
    token: {{ service_account_token }}