name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH Client and Rsync
        run: sudo apt-get install -y sshpass rsync

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          DEPLOY_DIR: /home/${{ secrets.SERVER_USER }}/K8-Health-Log-API
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "mkdir -p $DEPLOY_DIR"
          sshpass -p "$SERVER_PASSWORD" rsync -av -e "ssh -o StrictHostKeyChecking=no" . "$SERVER_USER@$SERVER_IP:$DEPLOY_DIR"
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "sudo chown -R $SERVER_USER:$SERVER_USER $DEPLOY_DIR && chmod -R 755 $DEPLOY_DIR"
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "cd $DEPLOY_DIR && chmod +x deploy.sh && ./deploy.sh"